import turtle

wn = turtle.Screen()
tortu=turtle.Turtle()
tortu.speed("fastest")
tortu.turtlesize(.1,.1,0)
tortu.pensize(3)

def banco():
    tortu.pencolor("blue")
    tortu.up()
    tortu.goto(-400,-200)
    tortu.down()
    tortu.goto(-200,-200)
    tortu.goto(-200,200)
    tortu.goto(0,200)
    tortu.goto(0,0)
    tortu.goto(75,0)
    tortu.up()
    tortu.goto(-400,-250)
    tortu.down()
    tortu.goto(-150,-250)
    tortu.goto(-150,150)
    tortu.goto(-50,150)
    tortu.goto(-50,-50)
    tortu.goto(75,-50)

def cuadrito(n,m):
    tortu.pencolor("black")
    tortu.up()
    tortu.goto(n,m)
    tortu.down()
    tortu.seth(90)
    tortu.forward(30)
    tortu.lt(90)
    tortu.forward(30)
    tortu.lt(90)
    tortu.forward(30)
    tortu.lt(90)
    tortu.forward(30)

def cuadro(j):
    tortu.pencolor("black")
    tortu.up()
    tortu.goto(200,j)
    tortu.down()
    tortu.seth(90)
    tortu.forward(100)
    tortu.seth(0)
    tortu.forward(100)
    tortu.seth(270)
    tortu.forward(100)
    tortu.seth(180)
    tortu.forward(100)

def llenado():
    banco()
    cuadro(150)
    cuadro(0)
    cuadro(-150)
    cuadro(-300)
    cuadrito(70,-40)
    cuadrito(30,-40)
    cuadrito(-10,-40)
    cuadrito(-10,0)
    cuadrito(-10,40)
    cuadrito(-10,80)
    cuadrito(-10,120)
    cuadrito(-10,160)
    cuadrito(-50,160)
    cuadrito(-120,160)
    cuadrito(-160,160)
    cuadrito(-160,120)
    cuadrito(-160,80)
    cuadrito(-160,40)
    cuadrito(-160,0)
    cuadrito(-160,-40)
    cuadrito(-160,-80)
    cuadrito(-160,-120)
    cuadrito(-160,-160)
    cuadrito(-160,-200)
    cuadrito(-160,-240)
    cuadrito(-200,-240)
    cuadrito(-240,-240)
    cuadrito(-280,-240)
    cuadrito(-320,-240)
    cuadrito(-360,-240)
    cuadro(150)

def estadocaja(caja,estado):
    if (estado=='0'):
        tortu.fillcolor('green')
        if (caja=='1'):
            tortu.fill(True)
            cuadro(150)
            tortu.fill(False)
        elif (caja=='2'):
            tortu.fill(True)
            cuadro(0)
            tortu.fill(False)
        elif (caja=='3'):
            tortu.fill(True)
            cuadro(-150)
            tortu.fill(False)
        elif (caja=='4'):
            tortu.fill(True)
            cuadro(-300)
            tortu.fill(False)
    else:
        tortu.fillcolor('red')
        if (caja=='1'):
            tortu.fill(True)
            cuadro(150)
            tortu.fill(False)
        elif (caja=='2'):
            tortu.fill(True)
            cuadro(0)
            tortu.fill(False)
        elif (caja=='3'):
            tortu.fill(True)
            cuadro(-150)
            tortu.fill(False)
        elif (caja=='4'):
            tortu.fill(True)
            cuadro(-300)
            tortu.fill(False)
            
llenado()
estadocaja('1','1')
estadocaja('4','0')

turtle.done()
wn.mainloop() 
